### ISSUE TITLE
Logger configuration

### ISSUE THREAD

**Issue by mpapenbr** [mpapenbr/iracelog-cli#60]
For each named logger the log level shoud be configurable and support hierarchical definitions.

```
loggers:
  level:
    main: info
    main.worker: warn
    main.worker.\d+: error
```
